#! /lusr/bin/tcsh -f
#Execution File

if ("$#argv" == "0") then
        set host = "localhost"
        set teamname = "myteam"
        set programname  = "client"
else if ("$#argv" == "1" ) then
        set host = "localhost"
        set teamname = $1
        set programname  = "client"
else if ("$#argv" == "2" ) then
        set host = $1
        set teamname = $2
        set programname  = "client"
else if ("$#argv" == "3" ) then
        set host = $2
        set teamname = $3
        set programname  = $1
else
        echo "Usage:  $0 <program-name> <host-name> <team>"
        exit -1
endif

#set simulator_step = 30

echo "Running with the following parameters"
echo "Hostname: " $host
echo "Team: " $teamname
echo "Program: " $programname
#echo "Sim_step: " $simulator_step

./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
./quicksleep
#./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
#./quicksleep
#./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
#./quicksleep
#./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
#./quicksleep
#./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
#./quicksleep
#./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
#./quicksleep
#./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
#./quicksleep
#./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
#./quicksleep
#./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
#./quicksleep
#./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
#./quicksleep
#./$programname -file client.conf -file ~/.rcssserver-server.conf -file ~/.rcssserver-player.conf -host $host -team_name $teamname &
#./quicksleep

